export const enum usersTypeActions {
  LOAD_USERS = '[LOAD_USERS] LOAD Users',
  LOAD_USERS_SUCCESS = '[LOAD_USERS_SUCCESS] LOAD Users with success',
  LOAD_USERS_FAIL = '[LOAD_USERS_FAIL] Dont LOAD Users',

  LOAD_USER = '[LOAD_USER] LOAD User',
  LOAD_USER_SUCCESS = '[LOAD_USER_SUCCESS] LOAD User with success',
  LOAD_USER_FAIL = '[LOAD_USER_FAIL] Dont LOAD User',

  CREATE_USER = '[CREATE_USER] CREATE User',
  CREATE_USER_SUCCESS = '[CREATE_USER_SUCCESS] CREATE User with success',
  CREATE_USER_FAIL = '[CREATE_USER_FAIL] Dont CREATE User',

  UPDATE_USER = '[UPDATE_USER] UPDATE User',
  UPDATE_USER_SUCCESS = '[UPDATE_USER_SUCCESS] UPDATE User with success',
  UPDATE_USER_FAIL = '[UPDATE_USER_FAIL] Dont UPDATE User',

  DELETE_USER = '[DELETE_USER] DELETE User',
  DELETE_USER_SUCCESS = '[DELETE_USER_SUCCESS] DELETE User with success',
  DELETE_USER_FAIL = '[DELETE_USER_FAIL] Dont DELETE User',
}
